### ISSUE TITLE
v6.0.0 docker-compose.yml mistake

### ISSUE THREAD

**Issue by vae520283995** [cardano-foundation/cardano-graphql#619]
CARDANO_GRAPHQL_VERSION is still 5.1.0
Can v6.0.0 be used in a production environment? I am using v5.1.0 now

**Comment by rhyslbw** [comment]
Thanks for the report @vae520283995 
The release has been corrected, and now includes the correct production-ready version:
https://github.com/input-output-hk/cardano-graphql/blob/6d496ae07f119c7bbcc0e1d6521897287941ca47/docker-compose.yml#L106
