### ISSUE TITLE
cardano-node-ogmios: cardano.node.DnsSubscription:Error:4022

### ISSUE THREAD

**Issue by zhy827827** [cardano-foundation/cardano-graphql#825]
### Ask a question

How to solve this issus？

cardano-graphql-800-cardano-node-ogmios-1  | [20d263ce:cardano.node.DnsSubscription:Error:4022] [2023-02-20 04:09:05.08 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: 3.130.47.105:3001 ExceededTimeLimit (Handshake) (ServerAgency TokConfirm)

cardano-graphql-800-cardano-node-ogmios-1  | [20d263ce:cardano.node.DnsSubscription:Error:4023] [2023-02-20 04:09:05.26 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: 18.182.219.85:3001 ExceededTimeLimit (Handshake) (ServerAgency TokConfirm)

cardano-graphql-800-cardano-node-ogmios-1  | [20d263ce:cardano.node.ErrorPolicy:Notice:145] [2023-02-20 04:12:37.19 UTC] IP 52.74.189.190:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
cardano-graphql-800-cardano-node-ogmios-1  | [20d263ce:cardano.node.ErrorPolicy:Notice:145] [2023-02-20 04:12:37.19 UTC] IP 35.156.63.196:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
cardano-graphql-800-cardano-node-ogmios-1  | [20d263ce:cardano.node.ErrorPolicy:Notice:145] [2023-02-20 04:12:37.19 UTC] IP 3.13.80.218:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
cardano-graphql-800-cardano-node-ogmios-1  | [20d263ce:cardano.node.ErrorPolicy:Notice:145] [2023-02-20 04:12:37.19 UTC] IP 52.57.122.128:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
cardano-graphql-800-cardano-node-ogmios-1  | [20d263ce:cardano.node.ErrorPolicy:Notice:145] [2023-02-20 04:12:37.19 UTC] IP 18.159.63.239:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s

![image](https://user-images.githubusercontent.com/15209848/220008023-6416d859-3238-48c3-98da-263564dddb9e.png)

**Comment by dawar330** [comment]
I am Facing the same Issue! Did you figure this out ?

**Comment by zhy827827** [comment]
There is no issue with the server of AWS. I suspect that the server IP is blacklisted

**Comment by yungtechboy1** [comment]
:/ Ive had my node running for almost 8 months, and I just recently updated GraphQL and I am getting the same errors!
