### ISSUE TITLE
RESTORE_SNAPSHOT: read from local file

### ISSUE THREAD

**Issue by aghamir** [cardano-foundation/cardano-graphql#833]
### Ask a question

Hi,
How I can set RESTORE_SNAPSHOT environment to read from local snapshot instead of url?

**Comment by a0ngo** [comment]
@aghamir assuming you're talking about `cardano-db-sync`, it will work with the absolute path.
See: 
https://github.com/IntersectMBO/cardano-db-sync/blob/master/nix/nixos/cardano-db-sync-service.nix#L85-L110

**Comment by Kammerlo** [comment]
Thanks @a0ngo ! If anything else let us know.
