### ISSUE TITLE
GraphQL query PaymentAddress not working on preprod

### ISSUE THREAD

**Issue by M2tec** [cardano-foundation/cardano-graphql#869]
### Summary

Query for address data is not working. We are trying to use a query for the Gamechanger wallet. Cardano-node and db-sync are fully synced. But asset metadata sync gets stuck at 11% on preprod. This could be related. 

### Steps to reproduce the bug

1. Go to http://localhost:3100  #Graphql playground
2. Query paymentAddresses data using the following query data:
[query.json](https://github.com/cardano-foundation/cardano-graphql/files/15190238/query.json)
[query_variables.json](https://github.com/cardano-foundation/cardano-graphql/files/15190239/query_variables.json)

![Playground_Query](https://github.com/cardano-foundation/cardano-graphql/assets/95027689/abc9b82f-6f90-4237-88a4-7e232275c6c8)

### Actual Result

Query results in an error: "TypeError: Cannot read properties of null (reading 'assetId')",

[error.json](https://github.com/cardano-foundation/cardano-graphql/files/15190320/error.json)

### Expected Result

A list of assetdata. With asset information. I have no working graphQL node to show actual correct output. 

### Environment

  
{
  os: {
    arch: 'x64',
    cpus: { count: 24, model: 'AMD Ryzen 9 7900X3D 12-Core Processor' },
    release: '6.8.0-31-generic',
    totalMem: 134160965632,
    type: 'Linux'
  },
  version: '8.0.0'
}

### Platform

- [X] Linux (Ubuntu)
- [ ] Linux (Other)
- [ ] macOS
- [ ] Windows

### Platform version

Ubuntu 24.04 LTS

### Runtime

- [ ] Node.js
- [X] Docker

### Runtime version

26.1.0

**Comment by M2tec** [comment]
Only 6 tokens with metadata seem to get added. 

"encode","name","firstAppearedInSlot"
"2cd858d024a08ec3049bbdc05e27dc894635de72b2b35d09f7cf8874","LaceCoin10",19.579.821
"34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518","ATADAnameless",10.749.595
"3e6dc4f1ef55bc8f0b5eff391c7f6dd97680872b3941ca0a535aa170","LaceCoin8",19.579.352
"68e897d04e26e9652f42aa785988e9ca0ed5fc7e69b2c12ef9c9d54c","LaceCoin9",19.579.627
"ee1ce9d7560f48a4ba3867037dbec2d8fed776d94dd6b00a35309073","SadCoin",11.103.293
"efbbf6498a4bed2e6fd8a4c7e1aa30e944502580f8dce8d76b47fd12","EmirCoin",36.061.711

There are also assets that have a firstAppearedInSlot close to the tip. So seems process is not aborting but just skipping most of the work. 

![image](https://github.com/cardano-foundation/cardano-graphql/assets/95027689/de13033e-d5d7-4555-b112-49b13aa21738)

**Comment by Kammerlo** [comment]
@M2tec Hi I just fixed your issue. Changes are in this branch: [fix/assets-skipped](https://github.com/cardano-foundation/cardano-graphql/tree/fix/assets-skipped )
My environment is still syncing, but the assets are now at 100%. Could you check it if it fixes your problem? 
Log from server component:
`{"name":"cardano-graphql","hostname":"d7e9401ef017","pid":1,"level":30,"module":"Server","msg":"Sync Progress: cardano-db-sync: 85.36% | Asset: 100%","time":"2024-05-03T08:49:43.897Z","v":0}`

**Comment by M2tec** [comment]
Hey yes. I just finished syncing. Query no longer returns an error. Awesome, thanks a lot!

Query result. 
[Query_data.json](https://github.com/cardano-foundation/cardano-graphql/files/15199027/Query_data.json)

**Comment by Kammerlo** [comment]
Perfect! I'm glad to hear that

**Comment by Kammerlo** [comment]
Closing this issue since the bugfix is now in PreRelease 8.0.2
If you have any other issues, let me know.
