### ISSUE TITLE
Are minFeeRefScriptCostPerByte and other Conway params available?

### ISSUE THREAD

**Issue by zxpectre** [cardano-foundation/cardano-graphql#891]
### Ask a question

Are `minFeeRefScriptCostPerByte` and other **Conway params** available?
I can see PlutusV3 cost models, not sure the other relevant params for Chang HF

**Comment by Kammerlo** [comment]
@zxpectre not yet, but they will be added soon. I'll add it here, when there's a PR

**Comment by Kammerlo** [comment]
Hey @zxpectre I just checked it, I saw that the parameters you are looking for are already available in the current version. They can be found within the `epoch_param` table. And you can query them like this: 
`query MyQuery {
  epoch_param(where: {epoch_no: {_eq: 508}}) {
    min_fee_ref_script_cost_per_byte
  }
}`

**Comment by Kammerlo** [comment]
We added the conway tables and data within this commit: https://github.com/cardano-foundation/cardano-graphql/commit/16ed6d71dbe95ff9e7d959ea51a8476da668684c

Additionally I will build a new release as soon as the new db-sync version is released for the node 9.2.0 so that I can bump the repsective versions.

**Comment by zxpectre** [comment]
Hi @Kammerlo, I can confirm table is not available on 8.2.2, I get `"message": "Cannot query field \"epoch_param\" on type \"Query\". Did you mean \"epochs_aggregate\"?",`  

Also, are we ready for Chang #2? 
I need to update our nodes versions, I'm ok to do so?. 
Not sure what else changes this time, cost models apparently yes.

Any estimated date for a new release with all these included?

**Comment by Kammerlo** [comment]
The update for chang2 will be released in a few days. I'm currently syncing from scratch and once it's done I'll release the HF ready version.

**Comment by zxpectre** [comment]
Thanks, it's being announced that Plomin/Chang 2 Hardfork hits preprod on 22nd November.

If you think 8.2.2 will work with node 10.1.2, cardano-db-sync 13.6.0.1 and ogmios 6.9.0 before the release, please let us know 🙏

**Comment by Kammerlo** [comment]
https://github.com/cardano-foundation/cardano-graphql/releases/tag/8.3.0 
Just released Version 8.3.0 which contains the latest Node + db-sync, let me know if you have any issues

**Comment by zxpectre** [comment]
Thanks @Kammerlo for fast releasing , so far so good. 2 preprods and 1 mainnet instances synced and ready.  
Don't have much time for further testing but if anything arise, will let you know
